<a href="https://colab.research.google.com/github/Bhuvana08/PROJECTS/blob/main/WISE_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Content/survey_lung_cancer.csv')

In [ ]:
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [ ]:
df.tail()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [ ]:
df.shape

(309, 16)

In [ ]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
AGE,309.0,62.673139,8.210301,21.0,57.0,62.0,69.0,87.0
SMOKING,309.0,1.563107,0.496806,1.0,1.0,2.0,2.0,2.0
YELLOW_FINGERS,309.0,1.569579,0.495938,1.0,1.0,2.0,2.0,2.0
ANXIETY,309.0,1.498382,0.500808,1.0,1.0,1.0,2.0,2.0
PEER_PRESSURE,309.0,1.501618,0.500808,1.0,1.0,2.0,2.0,2.0
CHRONIC DISEASE,309.0,1.504854,0.500787,1.0,1.0,2.0,2.0,2.0
FATIGUE,309.0,1.673139,0.469827,1.0,1.0,2.0,2.0,2.0
ALLERGY,309.0,1.556634,0.497588,1.0,1.0,2.0,2.0,2.0
WHEEZING,309.0,1.556634,0.497588,1.0,1.0,2.0,2.0,2.0
ALCOHOL CONSUMING,309.0,1.556634,0.497588,1.0,1.0,2.0,2.0,2.0
COUGHING,309.0,1.579288,0.494474,1.0,1.0,2.0,2.0,2.0
SHORTNESS OF BREATH,309.0,1.640777,0.480551,1.0,1.0,2.0,2.0,2.0
SWALLOWING DIFFICULTY,309.0,1.469256,0.499863,1.0,1.0,1.0,2.0,2.0
CHEST PAIN,309.0,1.556634,0.497588,1.0,1.0,2.0,2.0,2.0

In [ ]:
df.describe(include = 'all').transpose()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
GENDER,309,2,M,162,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGE,309.0,NaN,NaN,NaN,62.673139,8.210301,21.0,57.0,62.0,69.0,87.0
SMOKING,309.0,NaN,NaN,NaN,1.563107,0.496806,1.0,1.0,2.0,2.0,2.0
YELLOW_FINGERS,309.0,NaN,NaN,NaN,1.569579,0.495938,1.0,1.0,2.0,2.0,2.0
ANXIETY,309.0,NaN,NaN,NaN,1.498382,0.500808,1.0,1.0,1.0,2.0,2.0
PEER_PRESSURE,309.0,NaN,NaN,NaN,1.501618,0.500808,1.0,1.0,2.0,2.0,2.0
CHRONIC DISEASE,309.0,NaN,NaN,NaN,1.504854,0.500787,1.0,1.0,2.0,2.0,2.0
FATIGUE,309.0,NaN,NaN,NaN,1.673139,0.469827,1.0,1.0,2.0,2.0,2.0
ALLERGY,309.0,NaN,NaN,NaN,1.556634,0.497588,1.0,1.0,2.0,2.0,2.0
WHEEZING,309.0,NaN,NaN,NaN,1.556634,0.497588,1.0,1.0,2.0,2.0,2.0
ALCOHOL CONSUMING,309.0,NaN,NaN,NaN,1.556634,0.497588,1.0,1.0,2.0,2.0,2.0
COUGHING,309.0,NaN,NaN,NaN,1.579288,0.494474,1.0,1.0,2.0,2.0,2.0
SHORTNESS OF BREATH,309.0,NaN,NaN,NaN,1.640777,0.480551,1.0,1.0,2.0,2.0,2.0
SWALLOWING DIFFICULTY,309.0,NaN,NaN,NaN,1.469256,0.499863,1.0,1.0,1.0,2.0,2.0
CHEST PAIN,309.0,NaN,NaN,NaN,1.556634,0.497588,1.0,1.0,2.0,2.0,2.0
LUNG_CANCER,309,2,YES,270,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    object
dtypes: int64(14), object(2)
memory usage: 38.8+ KB

In [ ]:
df.columns

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'LUNG_CANCER'],
      dtype='object')

In [ ]:
df = df.drop(columns = ['YELLOW_FINGERS','PEER_PRESSURE','ALLERGY ','CHRONIC DISEASE','ALCOHOL CONSUMING'])

In [ ]:
df.head()

,GENDER,AGE,SMOKING,ANXIETY,FATIGUE,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,2,2,2,2,2,YES
1,M,74,2,1,2,1,1,2,2,2,YES
2,F,59,1,1,2,2,2,2,1,2,NO
3,M,63,2,2,1,1,1,1,2,2,NO
4,F,63,1,1,1,2,2,2,1,1,NO

In [ ]:
df.columns.nunique()

11

In [ ]:
df = pd.get_dummies(df)

In [ ]:
df.head()

,AGE,SMOKING,ANXIETY,FATIGUE,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_F,GENDER_M,LUNG_CANCER_NO,LUNG_CANCER_YES
0,69,1,2,2,2,2,2,2,2,0,1,0,1
1,74,2,1,2,1,1,2,2,2,0,1,0,1
2,59,1,1,2,2,2,2,1,2,1,0,1,0
3,63,2,2,1,1,1,1,2,2,0,1,1,0
4,63,1,1,1,2,2,2,1,1,1,0,1,0

In [ ]:
# Using dummies can increase the volume of data - called dummy variable trap

In [ ]:
df = df.drop(columns=['GENDER_M','LUNG_CANCER_NO'])
df.head()

,AGE,SMOKING,ANXIETY,FATIGUE,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_F,LUNG_CANCER_YES
0,69,1,2,2,2,2,2,2,2,0,1
1,74,2,1,2,1,1,2,2,2,0,1
2,59,1,1,2,2,2,2,1,2,1,0
3,63,2,2,1,1,1,1,2,2,0,0
4,63,1,1,1,2,2,2,1,1,1,0

In [ ]:
predictor = df.drop(columns=['LUNG_CANCER_YES'])
target = df['LUNG_CANCER_YES']

In [ ]:
predictor.head()

,AGE,SMOKING,ANXIETY,FATIGUE,WHEEZING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_F
0,69,1,2,2,2,2,2,2,2,0
1,74,2,1,2,1,1,2,2,2,0
2,59,1,1,2,2,2,2,1,2,1
3,63,2,2,1,1,1,1,2,2,0
4,63,1,1,1,2,2,2,1,1,1

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
predictor = ss.fit_transform(predictor)

In [ ]:
# predictor.head() - This will not execute because it is in array

In [ ]:
predictor[5]

array([ 1.50382491, -1.13529242, -0.99676897,  0.6968335 ,  0.892475  ,
        0.85220712,  0.74873631, -0.94029056, -1.12047956,  1.04978132])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(predictor,target,test_size=0.2,random_state = 0)

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(x_train,y_train)

lr_predict = lr.predict(x_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(lr_predict,y_test))

0.9032258064516129

In [ ]:
# SVM(KERNEL = 'RBF/LINEAR)
# NAIVE BAYES
# KNN
# DECISION TREE(CRITERION = 'GINI/ENTROPY')
# RANDOM FOREST(CRITERION = 'GINI/ENTROPY)

In [ ]:
# SVM
from sklearn.svm import SVC

svm = SVC(kernel='linear')

svm.fit(x_train,y_train)

svm_predicted = svm.predict(x_test)

print(accuracy_score(svm_predicted,y_test))

0.8387096774193549

In [ ]:
#rbf kernel
from sklearn.svm import SVC

svm = SVC(kernel='rbf')

svm.fit(x_train,y_train)

svm_predicted = svm.predict(x_test)

print(accuracy_score(svm_predicted,y_test))

0.8548387096774194

In [ ]:
#naive bayes
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(x_train,y_train)
gnb_predicted = gnb.predict(x_test)

print(accuracy_score(gnb_predicted,y_test))

0.8870967741935484

In [ ]:
# KNN

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)

neigh.fit(x_train,y_train)
neigh_predicted = neigh.predict(x_test)

print(accuracy_score(neigh_predicted,y_test))

0.8548387096774194

In [ ]:
#decision tree

from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='gini')
clf = clf.fit(x_train,y_train)

clf_predicted = clf.predict(x_test)

print(accuracy_score(clf_predicted,y_test))

0.8064516129032258

In [ ]:
clf_e = tree.DecisionTreeClassifier(criterion='entropy')
clf_e = clf_e.fit(x_train,y_train)

clfe_predicted = clf.predict(x_test)

print(accuracy_score(clfe_predicted,y_test))

0.8064516129032258

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(criterion='gini')
rfc = rfc.fit(x_train,y_train)

rfc_predicted = rfc.predict(x_test)

print(accuracy_score(rfc_predicted,y_test))

0.8709677419354839

In [ ]:
rfc_e = RandomForestClassifier(criterion='entropy')
rfc_e = rfc_e.fit(x_train,y_train)

rfce_predicted = rfc_e.predict(x_test)

print(accuracy_score(rfce_predicted,y_test))

0.8548387096774194

In [ ]:
from time import time
parameters = {'penalty' : ['l1', 'l2', 'elasticnet', None],
              'solver' : ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
              'max_iter' : [100, 200, 300, 400, 500],
              }
#we are checking in the different variation of numerical values
#in the parameters of random forest classifier

from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator = lr, # Make sure classifier points to the RF model
                           param_grid = parameters,
                           scoring = "accuracy",
                           cv = 10,#from k-fold validation
                           n_jobs = -1)#to use the entire core of the machine

t0 = time()#just to check how much time it takes to excute the program
grid_search = grid_search.fit(x_train, y_train)
t1 = time()
print("Took %0.2f seconds" % (t1 - t0))

rf_best_accuracy = grid_search.best_score_
rf_best_parameters = grid_search.best_params_
rf_best_accuracy, rf_best_parameters

Took 9.94 seconds

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning:
550 fits failed out of a total of 1200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver newton-cholesky supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 64, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver newton-cholesky supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1291, in fit
    fold_coefs_ = Parallel(n_jobs=self.n_jobs, verbose=self.verbose, prefer=prefer)(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 521, in _logistic_regression_path
    alpha = (1.0 / C) * (1 - l1_ratio)
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

--------------------------------------------------------------------------------
50 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1216, in fit
    self.coef_, self.intercept_, self.n_iter_ = _fit_liblinear(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py", line 1223, in _fit_liblinear
    solver_type = _get_liblinear_solver_type(multi_class, penalty, loss, dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py", line 1062, in _get_liblinear_solver_type
    raise ValueError(
ValueError: Unsupported set of arguments: The combination of penalty='None' and loss='logistic_regression' is not supported, Parameters: penalty=None, loss='logistic_regression', dual=False

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan 0.87              nan        nan        nan 0.87
 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667
        nan        nan        nan        nan        nan        nan
 0.87016667        nan 0.87016667 0.87016667 0.87016667 0.87016667
        nan 0.87              nan        nan        nan 0.87
 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667
        nan        nan        nan        nan        nan        nan
 0.87016667        nan 0.87016667 0.87016667 0.87016667 0.87016667
        nan 0.87              nan        nan        nan 0.87
 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667
        nan        nan        nan        nan        nan        nan
 0.87016667        nan 0.87016667 0.87016667 0.87016667 0.87016667
        nan 0.87              nan        nan        nan 0.87
 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667
        nan        nan        nan        nan        nan        nan
 0.87016667        nan 0.87016667 0.87016667 0.87016667 0.87016667
        nan 0.87              nan        nan        nan 0.87
 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667 0.87416667
        nan        nan        nan        nan        nan        nan
 0.87016667        nan 0.87016667 0.87016667 0.87016667 0.87016667]
  warnings.warn(

(0.8741666666666668, {'max_iter': 100, 'penalty': 'l2', 'solver': 'lbfgs'})